[window]
opacity = 0.9

[font]
normal = { family = 'CamingoCode Nerd Font Mono' }
size = 10.5

[colors.primary]
background = '#263238'
foreground = '#a1b0b8'

[colors.normal]
black =		'#252525'
red =		'#ff5252'
green =		'#c3d82c'
yellow =	'#ffc135'
blue =		'#42a5f5'
magenta =	'#d81b60'
cyan =		'#00acc1'
white =		'#f5f5f5'

[colors.bright]
black =		'#708284'
red =		'#ff5252'
green =		'#c3d82c'
yellow =	'#ffc135'
blue =		'#42a5f5'
magenta =	'#d81b60'
cyan =		'#00acc1'
white =		'#f5f5f5'
