#!/bin/sh

NAME=$(git config user.name)
EMAIL=$(git config user.email)

if [ -z "$NAME" ]; then
    echo "empty git config user.name"
    exit 1
fi

if [ -z "$EMAIL" ]; then
    echo "empty git config user.email"
    exit 1
fi

# If the Signed-off-by isn't already present on the commit, add it.
grep Signed-off-by "$1" || git interpret-trailers \
    --if-exists doNothing \
    --trailer "Signed-off-by: $NAME <$EMAIL" \
    --in-place "$1"
